name: kaloree
description: "Food detection and calorie measurement app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  cloud_firestore: ^4.15.8
  connectivity_plus: ^6.0.1
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  gap: ^3.0.1
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  image: ^4.1.7
  image_cropping: ^0.0.14
  image_picker: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_gauges: ^25.1.38
  tflite_flutter: ^0.10.4
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/models/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21