name: kaloree
description: "Food detection and calorie measurement app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  connectivity_plus: ^6.0.1
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get_it: ^7.6.7
  image: ^4.1.7
  image_cropping: ^0.0.14
  image_picker: ^1.0.8
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_gauges: ^25.1.38
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/models/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
